gchq/Bailo

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- package-lock.json
- package.json
- pages/deployment/[uuid].tsx
- server/processors/processDeployments.ts
- server/routes/v1/registryAuth.ts
- server/scripts/triggerDeployment.ts
This PR removes the dependency on Docker from our deployments, migrating images between namespaces using simple fetch requests.
> Remove docker daemon from deployments

- pages/deployment/[uuid].tsx
- pages/deployments.tsx
- pages/review.tsx
- Added some checks to the review page so any missing data wouldn't cause the page to crash
- Added a helpful warning alert to tell users that data was missing from models/deployments needing a review
- Altered the filter section of the "My Deployments"
> made some minor adjustments to review and deployment page

- .gitignore
- .prettierignore
- jest.config.ts
Include only files that we want to test.
> Update Jest Reports for Coverage

- .eslintrc.js
- next.config.js
- pages/deployment/[uuid].tsx
- pages/model/[uuid]/deploy.tsx
- pages/model/[uuid]/edit/[version].tsx
- pages/model/[uuid]/new-version.tsx
- pages/upload.tsx
- src/Form/Form.tsx
- src/Form/FormDesigner.tsx
- src/Form/FormUpload.tsx
- src/Form/ModelEditSubmission.tsx
- src/Form/ModelExportAndSubmission.tsx
- src/Form/RenderBasicFileTab.tsx
- src/Form/RenderButtons.tsx
- src/Form/RenderFileTab.tsx
- src/Form/RenderForm.tsx
- types/interfaces.ts
- utils/complianceFlow.ts
- utils/dateUtils.ts
- utils/fetcher.ts
- utils/formUtils.ts
- utils/mockJsdom.ts
- utils/propertyUtils.ts
- utils/uiSchemaUtils.ts
- utils/useCacheVariable.ts
Mostly Typescript issues, a few changes of functions -> React elements.
> Fix linting issues in utils

- data/requests.ts
- pages/review.tsx
- server/routes/v1/requests.ts
Added fix so deployments work o the archived tab
> changed requestObj.version... to requestObj.status

- server/scripts/listRegistryImages.ts
This was useful for some of the debugging I was doing today.
> Add list registry images script

- server/scripts/example_schemas/minimal_upload_schema.json
> Regex limitation on version field

- package-lock.json
- package.json
We don't actually seem to use it anywhere...
> Remove Babel Module Resolver

- pages/deployment/[uuid].tsx
- pages/model/[uuid].tsx
- server/migrations/002-user-array-support.ts
- server/models/Deployment.ts
- server/models/Version.ts
- server/processors/processUploads.ts
- server/routes/v1/approvals.ts
- types/interfaces.ts
Previously sent it to `req.user._id`, which is incorrect.  It should be the owners of the model / deployment.
> Fix email target on approval emails

- backend/src/utils/MinioStore.ts
An awkwardly small fix for this problem.
> Allow large file uploads

- .github/workflows/build.js.yml
> Split out frontend and backend builds

- infrastructure/helm/bailo/templates/bailo/bailo.configmap.yaml
- infrastructure/helm/bailo/values.yaml
updated stroom to use values.yaml for production.js
> fix stroom

- frontend/src/ModelOverview.tsx
- frontend/src/common/DisabledElementTooltip.spec.tsx
- frontend/src/common/HelpPopover.spec.tsx
- frontend/src/common/HelpPopover.tsx
- frontend/utils/testUtils.ts
A question mark is displayed to each field on a model card (MSRO, MTR and MO) so that when hovered over, it  will display their full description.
A unit test has also been implemented.
> added question mark to fields

- .github/workflows/build.js.yml
- backend/src/external/Authorisation/AuthorisationOAuth.ts
- frontend/cypress/e2e/model.cy.ts
configured use Secuirty context
removed host config for Mongo, now managed my _helper.tpl
> Action K8s

- backend/config/default.cjs
- backend/config/docker_compose.cjs
- backend/src/utils/smtp.ts
- lib/python/setup.py
Tested locally (docker-compose), LS Openshift (dev), and HS
> Update smtp auth to be undefined if auth is not required

- .prettierignore
- .vscode/extensions.json
- .vscode/settings.json
- lib/python-beta/.gitignore
- lib/python-beta/.pre-commit-config.yaml
- lib/python-beta/.pypirc
- lib/python-beta/README.md
- lib/python-beta/docs/Makefile
- lib/python-beta/docs/bailo.bailo.rst
- lib/python-beta/docs/bailo.rst
- lib/python-beta/docs/conf.py
- lib/python-beta/docs/index.rst
- lib/python-beta/docs/make.bat
- lib/python-beta/docs/modules.rst
- lib/python-beta/docs/pre-commit-config.md
- lib/python-beta/docs/pylint.md
- lib/python-beta/docs/pyproject.md
- lib/python-beta/docs/requirements.txt
- lib/python-beta/examples/create_model.py
- lib/python-beta/pyproject.toml
- lib/python-beta/src/bailo/__init__.py
- lib/python-beta/src/bailo/bailo.py
- lib/python-beta/src/bailo/enums.py
- lib/python-beta/tests/conftest.py
- lib/python-beta/tests/test_client.py
Currently implements two basic functions.  Has working tests with mocking.  Does not have great documentation.
> Initial Python library rewrite

- lib/python-beta/src/bailo/bailo.py
- lib/python-beta/tests/test_client.py
- get_model
- update_model
- get_model_card
- update_model_card
- model_card_from_schema
> New endpoints (including unit tests and docstrings)

- lib/python-beta/src/bailo/bailo.py
- lib/python-beta/tests/test_client.py
Ticket: [BAI-903](https://jira.tdx.gss.gov.uk/browse/BAI-903)
- get_reviews method created, along with docstring and unit test.
> Added get_reviews method.

- frontend/src/model/beta/accessRequests/AccessRequestDisplay.tsx
- frontend/src/model/beta/registry/ModelImageDisplay.tsx
- frontend/src/model/beta/releases/ReleaseDisplay.tsx
- frontend/src/reviews/ReviewComment.tsx
- frontend/src/reviews/ReviewDecision.tsx
> updated bordered boxes to use MUI outlined cards

- .github/workflows/build.js.yml
- .github/workflows/python.yml
- lib/examples/example_model_code/Model.py
- lib/examples/example_model_code/basemodel/__init__.py
- lib/examples/example_model_code/basemodel/basemodel.py
- lib/python-beta/.pre-commit-config.yaml
- lib/python-beta/README.md
- lib/python-beta/pyproject.toml
- lib/python-beta/src/bailo/__init__.py
- lib/python-beta/src/bailo/core/__init__.py
- lib/python-beta/src/bailo/core/agent.py
- lib/python-beta/src/bailo/core/client.py
- lib/python-beta/src/bailo/core/enums.py
- lib/python-beta/src/bailo/core/exceptions.py
- lib/python-beta/src/bailo/core/utils.py
- lib/python-beta/src/bailo/helper/__init__.py
- lib/python-beta/src/bailo/helper/access_request.py
- lib/python-beta/src/bailo/helper/model.py
- lib/python-beta/src/bailo/helper/release.py
- lib/python-beta/src/bailo/helper/schema.py
- lib/python-beta/tests/conftest.py
- lib/python-beta/tests/test_access_request.py
- lib/python-beta/tests/test_client.py
- lib/python-beta/tests/test_model.py
- lib/python-beta/tests/test_schema.py
This Github action covers:
- Integration and Unit testing
- LInting with Pylint
- Formatting with Black
Errors are expected with linting
> Migrate python CI/CD to python-beta

- frontend/src/MessageAlert.tsx
> Add contact support team to each error message

- infrastructure/helm/bailo/templates/mail/mail.deployment.yaml
- infrastructure/helm/bailo/templates/nginx/nginx.deployment.yaml
- infrastructure/helm/bailo/templates/registry/registry.deployment.yaml
- infrastructure/helm/bailo/values.yaml
- added security context and image pull secrets
- change default built to img from openshift
> added sec context

- frontend/src/Form/beta/JsonSchemaForm.tsx
> added a custom object field for forms so we can indent nested objects

- .gitlab-ci.yml
> update gitlab ci

- infrastructure/helm/bailo/templates/bailo/bailo.deployment.yaml
remove stroom from deployment file
> remove stroom

- backend/src/models/Model.ts
- backend/src/services/model.ts
- Adds increased weight to key fields
- Sort by 'matchScore'
> Improve model search

- frontend/package-lock.json
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/pages/_document.tsx
This updates Bailo inline with these [docs](https://mui.com/material-ui/integrations/nextjs/). However no performance change can be observed from this change.
> Update nextjs integration

- frontend/pages/model/[modelId]/access-request/[accessRequestId]/review.tsx
- frontend/pages/model/[modelId]/release/[semver]/review.tsx
- frontend/src/model/overview/ModelCardRevisionListDisplay.tsx
- frontend/src/wrapper/TopNavigation.tsx
Also included new redirects for reviewing releases and access requests (they redirect back to the relevant page, _not_ the model page)
> various frontend changes

- backend/src/scripts/example_schemas/minimal_model_schema.json
- frontend/package-lock.json
- frontend/pages/model/new.tsx
- frontend/pages/schemas/new.tsx
- frontend/src/Form/JsonSchemaForm.tsx
- frontend/src/MuiForms/CustomTextInput.tsx
- frontend/src/MuiForms/RichTextInput.tsx
- frontend/src/MuiForms/TagSelector.tsx
- frontend/src/common/RichTextEditor.tsx
- frontend/src/model/ModelNameInput.tsx
- frontend/src/model/releases/ReleaseForm.tsx
- frontend/src/model/settings/ModelAccess.tsx
- frontend/src/model/settings/ModelDetails.tsx
> Revert "added auto focus to first question of json schema forms"

- frontend/pages/review.tsx
- frontend/src/reviews/ReviewItem.tsx
- frontend/src/reviews/ReviewsList.tsx
- frontend/src/reviews/ReviewsListContainer.tsx
- frontend/types/types.ts
> changed how reviews are displayed on review page

- backend/src/routes/v2/model/getModel.ts
- backend/src/services/model.ts
- backend/test/services/model.spec.ts
- frontend/actions/model.ts
- frontend/pages/data-card/[dataCardId].tsx
- frontend/pages/data-card/[dataCardId]/schema.tsx
- frontend/pages/model/[modelId].tsx
- frontend/pages/model/[modelId]/access-request/[accessRequestId]/review.tsx
- frontend/pages/model/[modelId]/access-request/new.tsx
- frontend/pages/model/[modelId]/inference/[image]/[tag].tsx
- frontend/pages/model/[modelId]/inference/new.tsx
- frontend/pages/model/[modelId]/release/[semver]/review.tsx
- frontend/pages/model/[modelId]/release/new.tsx
- frontend/pages/model/[modelId]/schema.tsx
- frontend/src/entry/model/inferencing/EditableInference.tsx
- frontend/src/entry/model/releases/EditableRelease.tsx
- frontend/src/entry/model/settings/ModelAccess.tsx
- frontend/src/entry/overview/FormEditPage.tsx
- frontend/src/schemas/SchemaSelect.tsx
This prevents models from using data card pages/components and vice versa.
> Added optional kind query param to getModel endpoint

- backend/src/models/Review.ts
- backend/test/routes/review/__snapshots__/postAccessRequestReviewResponse.spec.ts.snap
- backend/test/routes/review/__snapshots__/postReleaseReviewResponse.spec.ts.snap
- frontend/actions/review.ts
- frontend/pages/model/[modelId]/access-request/[accessRequestId]/review.tsx
- frontend/pages/model/[modelId]/release/[semver]/review.tsx
- frontend/src/common/ReviewWithComment.tsx
- frontend/src/entry/model/reviews/ReviewDisplay.tsx
- frontend/src/reviews/ReviewDecisionDisplay.tsx
- frontend/types/types.ts
This option will only appear if you have already made a review as the selected role.
> added a third option for reviews so users can undo their previous review

- lib/python/docs/notebooks/models_and_releases_demo_pytorch.ipynb
- lib/python/src/bailo/__init__.py
- lib/python/src/bailo/core/agent.py
- lib/python/src/bailo/core/client.py
- Now reads env variables or cli input
> BAI-1286 TokenAgent Improvements

- frontend/package-lock.json
- frontend/package.json
- frontend/tsconfig.json
- frontend/vitest.config.mts
Bumps frontend vitest dependency to satisfy warning in VScode testing plugin
> Bump frontend vitest

- README.md
- backend/Dockerfile
- backend/Dockerfile.dev
- backend/nodemon.json
- backend/package-lock.json
- backend/package.json
- backend/src/scripts/runScript.ts
- backend/tsconfig.json
- frontend/Dockerfile
- frontend/Dockerfile.dev
- frontend/pages/docs/administration/helm/isolated-environments.mdx
This updates Node to 22.  It requires https://github.com/gchq/Bailo/pull/1387 to be merged in.
> 2. Update Node from 18 to 22

- frontend/actions/response.ts
- frontend/src/reviews/EditableReviewComment.tsx
- frontend/src/reviews/ReviewCommentDisplay.tsx
- frontend/src/reviews/ReviewComments.tsx
- frontend/src/reviews/ReviewDecisionDisplay.tsx
- frontend/types/types.ts
- frontend/utils/dateUtils.ts
- frontend/utils/test/testModels.ts
> added the ability to edt comments via the UI

- frontend/src/entry/model/settings/EntryRolesInfo.tsx
> added a better description of general role permissions to UI

- backend/src/routes/v2/release/postRelease.ts
- backend/src/routes/v2/release/putRelease.ts
- frontend/src/Form/EditableFormHeading.tsx
- frontend/src/entry/model/releases/EditableRelease.tsx
> added release note validation to put and post release

- backend/package-lock.json
- backend/package.json
> Revert "Bump @aws-sdk/client-cognito-identity-provider from 3.637.0 to 3.667.0 in /backend"

- lib/modelscan_api/.gitignore
- lib/modelscan_api/.pre-commit-config.yaml
- lib/modelscan_api/README.md
- lib/modelscan_api/bailo_modelscan_api/__init__.py
- lib/modelscan_api/bailo_modelscan_api/config.py
- lib/modelscan_api/bailo_modelscan_api/dependencies.py
- lib/modelscan_api/bailo_modelscan_api/main.py
- lib/modelscan_api/bailo_modelscan_api/test_main.py
- lib/modelscan_api/requirements-dev.txt
- lib/modelscan_api/requirements.txt
https://github.com/protectai/modelscan is a Python tool to scan model artefacts. It is installed via Pip and then can be interacted with via the Python library or the CLI.
We need it to be accessible via a REST API.
The new application will be added here: https://github.com/gchq/Bailo/tree/main/lib
> BAI-1500 ModelScan REST API

- .github/workflows/build.js.yml
- .github/workflows/python-publish-test.yml
- .github/workflows/python-publish.yml
- .github/workflows/web.yml
As per #1613, address the deprecation of artifact v3.
> Replace GitHub artifact v3 with v4

- lib/modelscan_api/bailo_modelscan_api/main.py
This allows multiple requests to be handled by the ModelScan API simultaneously.
> make api endpoints async and modelscan instantiate per-thread

- Dockerfile.standalone
- backend/Dockerfile
- frontend/Dockerfile
- frontend/Dockerfile.dev
As per https://docs.docker.com/reference/build-checks/legacy-key-value-format/
> replace dockerfile LegacyKeyValueFormat

- frontend/pages/docs/administration/getting-started/app-configuration.mdx
- frontend/pages/docs/administration/helm/configuration.mdx
- frontend/pages/docs/administration/helm/isolated-environments.mdx
- frontend/pages/docs/administration/schemas/create-a-schema.mdx
- frontend/pages/docs/administration/schemas/upload-a-schema.mdx
- frontend/pages/docs/directory.tsx
- frontend/pages/docs/users/managing-models-and-releases/upload-to-bailo/files.mdx
- frontend/pages/docs/users/programmatically-using-bailo/open-api.mdx
- frontend/pages/docs/users/programmatically-using-bailo/python-client.mdx
- frontend/pages/docs/users/reviews/reviewed/access-request.mdx
- frontend/pages/docs/users/reviews/reviewed/releases.mdx
- frontend/pages/docs/users/using-a-model/using-a-pushed-docker-image.mdx
Fixes #1574 among other things
> BAI-1499 fix dead links, correct typos and improve docs

- .husky/pre-commit
See: https://github.com/typicode/husky/releases/tag/v9.1.1
> Removed deprecated lines from husky pre-commit

- backend/package-lock.json
- backend/package.json
Fix for https://github.com/gchq/Bailo/security/dependabot/118 
https://github.com/mjmlio/mjml/issues/2589#issuecomment-2575582869
> Update mjml due to vulnerability

- backend/src/services/release.ts
Fix `$lookup with 'pipeline' may not specify 'localField' or 'foreignField'` problem for users with older versions of MongoDB by making `getModelReleases` `Release.aggregate.[...]lookup` backward compatible for MongoDB <=4.4.
> Backwards compatibility for MongoDB <=4.4

- backend/docs/notebooks/experiment_tracking_demo.ipynb
- lib/python/README.md
- lib/python/src/bailo/core/utils.py
- lib/python/src/bailo/helper/entry.py
- lib/python/src/bailo/helper/model.py
- lib/python/src/bailo/helper/release.py
- lib/python/src/bailo/helper/schema.py
- lib/python/tests/conftest.py
- lib/python/tests/test_model.py
Fix mlflow test_import_model_no_schema test and improve python linting and docs
> MLFlow tests, linting & docs

- .github/workflows/build.js.yml
- backend/docs/notebooks/datacards_demo.ipynb
- backend/docs/notebooks/experiment_tracking_demo.ipynb
- frontend/pages/docs/users/programmatically-using-bailo/python-client.mdx
- lib/python/README.md
- lib/python/pyproject.toml
Migrate Python client MLFlow package to optional-dependency and add MLFlow integration tests to GitHub Workflow.
> MLFlow to optional dependency

- frontend/src/entry/overview/TemplatePage.tsx
> Fixed an issue stopping data cards being created

- lib/python/src/bailo/helper/access_request.py
- lib/python/src/bailo/helper/datacard.py
- lib/python/src/bailo/helper/entry.py
- lib/python/src/bailo/helper/model.py
- lib/python/src/bailo/helper/release.py
- lib/python/src/bailo/helper/schema.py
Fixing issue #1889 by removing the f-string when % formatting is used.
> Issue #1889: Optimise Python Client Logger Strings

- docker-compose-prod.yml
- docker-compose.yml
As per https://github.com/bitnami/containers/issues/81607
> Replicated changes from bugfix/fix-minio-not-starting

- backend/src/routes/v2/model/file/patchFile.ts
- backend/src/services/file.ts
- backend/test/services/__snapshots__/file.spec.ts.snap
- backend/test/services/file.spec.ts
> rewrite updateFile to process all patchFileParams and update tests

- lib/python/src/bailo/core/agent.py
- lib/python/src/bailo/core/client.py
- lib/python/src/bailo/core/enums.py
- lib/python/src/bailo/core/exceptions.py
- lib/python/src/bailo/core/utils.py
> Add and improve bailo core docs

- frontend/package-lock.json
- frontend/package.json
- frontend/pages/model/[modelId]/access-request/new.tsx
- frontend/pages/model/[modelId]/inference/new.tsx
- frontend/pages/model/[modelId]/release/new.tsx
- frontend/pages/model/[modelId]/template.tsx
- frontend/pages/reviewRoles/new.tsx
- frontend/pages/schemas/new.tsx
- frontend/pages/settings/personal-access-tokens/new.tsx
- frontend/src/Form/EditableFormHeading.tsx
- frontend/src/common/ReviewWithComment.tsx
- frontend/src/entry/CreateEntry.tsx
- frontend/src/entry/model/accessRequests/EditableAccessRequestForm.tsx
- frontend/src/entry/model/files/FileUploadDialog.tsx
- frontend/src/entry/model/mirroredModels/ExportModelAgreement.tsx
- frontend/src/entry/model/mirroredModels/ExportSettings.tsx
- frontend/src/entry/model/settings/AccessRequestSettings.tsx
- frontend/src/entry/model/settings/TemplateSettings.tsx
- frontend/src/entry/overview/SaveAndCancelFormButtons.tsx
- frontend/src/entry/settings/DangerZone.tsx
- frontend/src/entry/settings/EntryAccessTab.tsx
- frontend/src/entry/settings/EntryDetails.tsx
- frontend/src/reviews/ReviewComments.tsx
- frontend/src/schemas/SchemaButton.tsx
- frontend/src/settings/authentication/AuthenticationTab.tsx
https://mui.com/material-ui/migration/upgrade-to-v6/#button-with-loading-state
Part of #2117
> Replace `LoadingButton` with `Button` and remove `mui-lab` dependency

- backend/config/default.cjs
- backend/src/connectors/fileScanning/Base.ts
- backend/src/connectors/fileScanning/clamAv.ts
- backend/src/connectors/fileScanning/modelScan.ts
- infrastructure/helm/bailo/templates/bailo/bailo.configmap.yaml
- infrastructure/helm/bailo/values.yaml
- More consistent Scanner logs with more comprehensive details.
- Add missing configmaps.
- Reduce default Scanners concurrency.
> Improve Scanner logs & update config
