gchq/Bailo

src/common/FormTabs.tsx
When editing a version the model card version field has been disabled.
=> disabled model card version field in upload form in edit mode

pages/deployment/[uuid].tsx, server/utils/queues.ts
When images are built the 'pull' length might be long, exceeding the default time period.  This sometimes causes jobs to be retried.  This pull request increases the stall interval to 120 seconds.
This was dodgy in the past because generally our image pulls are very fast, taking less than a second.  The issue arose when the docker cache was empty resulting in a long pull from Dockerhub.
I found I could reproduce the issue with:
```
docker rmi $(docker images -a --filter=dangling=true -q)
docker rm $(docker ps --filter=status=exited --filter=status=created -q)
```
=> Increase stall interval for queue uploads

helm/README.md, helm/bailo/createSecrets.ts, helm/bailo/values.yaml
This allows the secret creation to only be run the first time.  Otherwise, secrets get out of sync when `helm update` is run in the future.
=> Separate secret creation & installing of helm chart steps

package-lock.json, package.json, server/index.ts, server/utils/logger.ts
To fix asynchronous error handling, we need to use Express v5.  It has already gone through 8 alpha versions to improve stability and has been stabilizing for 7 years.  I'm not sure why it hasn't been released yet.
=> Bump Express to v5 to fix error handling

.github/workflows/node.js.yml, .github/workflows/style.js.yml, .github/workflows/unit.js.yml, .github/workflows/web.yml
Splits out style & unit tests from the E2E tests we run.  Saves ~2 minutes from runtime.  Also, doesn't break the unit / e2e tests if the style tests fail!
=> Split out some steps from the main CI workflow to reduce processing time

data/admin.ts
Array was previously defined as `filter[0]=misc&filter[1]=another&filter[2]=different`, but Express expects `filter=misc&filter=another&filter=different`.  This parameter changes how qs handles arrays.
=> Fix 400 issue when getting logs from loading pages.

frontend/pages/model/[uuid]/deploy.tsx, frontend/utils/formUtils.ts
Before it would add misc data to the highLevelDetails field due to it being a reference clone.  With clone deep we prevent that from happening.
=> Deep clone deployment data so deployment can be submitted twice

frontend/src/Form/RenderButtons.tsx, frontend/src/common/Snackbar.tsx
The error notification originally appeared from the bottom left. This has now been adjusted to appear at the bottom center, to be consistent with how server errors are presented.
=> corrected position of error notification

backend/package-lock.json, backend/package.json, backend/src/routes.ts, backend/src/routes/v1/approvals.ts, backend/src/routes/v1/deployment.ts, backend/src/routes/v1/version.ts, backend/src/services/approval.ts, backend/vitest.config.ts, frontend/components/wrapper/Wrapper.tsx, frontend/components/wrapper/WrapperIcon.tsx, frontend/data/approvals.ts, frontend/package-lock.json, frontend/package.json, frontend/pages/deployment/[uuid].tsx, frontend/pages/model/[uuid].tsx, frontend/src/Form/DeploymentSubmission.spec.tsx, frontend/src/Form/Form.spec.tsx, frontend/src/Form/ModelEditSubmission.spec.tsx, frontend/src/Form/ModelExportAndSubmission.spec.tsx, frontend/src/Wrapper.tsx, frontend/src/common/ApprovalsChip.spec.tsx, frontend/src/common/ApprovalsChip.tsx, frontend/src/common/ConfirmationDialogue.spec.tsx, frontend/src/common/FileInput.spec.tsx, frontend/utils/test/testModels.ts, frontend/utils/test/testUtils.ts, frontend/utils/testUtils.ts, frontend/vitest.config.ts
Have added complete functionality so that if the user has permissions to approve a model, they can do so directly from the model page, rather than having to navigate to Review. The button has been updated to reflect this and improve user experience.
One outstanding issue that has been noted is that the badges that display the 'count' of approvals (how many are remaining to be reviewed) are not synchronised on the approve button on the model page and on the Review option, as we are not using a state sharing solution like Redux. 
Scenario example: If there are 2 approvals to be made and you are the approver for both, and you are on the model page, you will see a badge displaying '2' on the button on that page and on the Review tab on the left side of the screen. If you select to approve …
=> Bai 551 approve reject directly from model

backend/config/default.cjs, backend/src/routes/v1/specification.ts, backend/src/types/types.ts, backend/src/utils/config.ts, frontend/pages/model/[uuid]/new-version.tsx, frontend/pages/upload.tsx, frontend/src/Form/RenderFileTab.tsx, frontend/src/common/Loading.tsx, frontend/types/types.ts, frontend/utils/byteUtils.ts
Added functionality so that if the user tries to upload a combination of code, binary and docker files (or any one of these) that exceeds the maximum upload size we allow, they are presented with an error message which tells them the issue, what the upper limit is, and they cannot proceed to select upload.
The amount set is configurable and at the time of this PR is set within backend>config>default.cjs to 50 GB.
This PR also includes an improved Loading state which displays a loading spinner rather than a Wrapper, which was confusing to the user and not visually attractive.
=> Bai 650 add warning message for max model upload size

backend/nodemon.json
These come up on every restart and don't particularly matter.  We already realise we're using multiple experimental features and these warnings just pollute the logs.
=> Hide experimental warnings from node

backend/src/connectors/v2/authorisation/index.ts, backend/src/connectors/v2/authorisation/silly.ts, backend/src/models/v2/Release.ts, backend/src/routes/v2/release/deleteRelease.ts, backend/src/routes/v2/release/getRelease.ts, backend/src/routes/v2/release/getReleases.ts, backend/src/routes/v2/release/postRelease.ts, backend/src/services/v2/release.ts, backend/test/routes/model/release/__snapshots__/deleteRelease.spec.ts.snap, backend/test/routes/model/release/__snapshots__/getRelease.spec.ts.snap, backend/test/routes/model/release/__snapshots__/getReleases.spec.ts.snap, backend/test/routes/model/release/__snapshots__/postRelease.spec.ts.snap, backend/test/routes/model/release/deleteRelease.spec.ts, backend/test/routes/model/release/getRelease.spec.ts, backend/test/routes/model/release/getReleases.spec.ts, backend/test/routes/model/release/postRelease.spec.ts, backend/test/services/__snapshots__/release.spec.ts.snap, backend/test/services/release.spec.ts, backend/test/testUtils/routes.ts
Adds create, list, get and delete endpoints and their corresponding services.
=> Add release endpoints

backend/src/models/v2/Model.ts, backend/src/scripts/example_schemas/minimal_access_request_schema_beta.json, backend/src/services/v2/schema.ts, frontend/pages/beta/index.tsx, frontend/pages/beta/model/[modelId].tsx, frontend/pages/beta/model/[modelId]/access/new.tsx, frontend/pages/beta/model/[modelId]/access/schema.tsx, frontend/pages/beta/model/[modelId]/schema.tsx, frontend/src/Form/beta/ModelCardForm.tsx, frontend/src/common/PageWithTabs.tsx, frontend/src/model/beta/Settings.tsx, frontend/src/model/beta/common/SchemaButton.tsx, frontend/src/model/beta/common/ValidationErrorIcon.tsx, frontend/src/model/beta/settings/AccessRequestSettings.tsx, frontend/src/model/beta/settings/ModelAccess.tsx, frontend/types/enums.ts, frontend/types/v2/types.ts, frontend/utils/uiSchemaUtils.ts
Changed living doc step labels to be consistent:
Added a "Request access" button:
This loads a select schema page (this could very easily change in the future!:
Added a form page for making an access request:
This also has validation:
=> add start of ui work for access requests

lib/python-beta/src/bailo/bailo.py, lib/python-beta/src/bailo/enums.py, lib/python-beta/tests/test_client.py
Additions:
- SchemaKind enum
- simple_upload method
- get_all_schemas method
- get_schema method
- create_schema method
- get_model roles method
- get_team method
- update_team method
=> Added schema, team and simple file upload methods.

lib/python-beta/pyproject.toml, lib/python-beta/src/bailo/bailo.py, lib/python-beta/tests/test_client.py
As discussed in ticket: [BAI-884](https://jira.tdx.gss.gov.uk/browse/BAI-884) and [BAI-902](https://jira.tdx.gss.gov.uk/browse/BAI-902)
- Using the validators library for URL validation.
- Renamed 'update' methods to 'patch' or 'put'. Renamed find_models to get_models.
=> Implemented URL validation on client initialisation & renamed methods to better align with HTTP requests

frontend/actions/release.ts, frontend/src/model/beta/releases/DraftNewReleaseDialog.tsx, frontend/types/v2/types.ts
Files can now be uploaded as part of a release. The files are individually uploaded, and the `id` of each is added to the release model.
Currently we are just displaying those `id`s on the release display, but in the future we will expand on this.
=> added file uploads to post releases

lib/python-beta/src/bailo/core/agent.py, lib/python-beta/src/bailo/core/client.py, lib/python-beta/src/bailo/core/enums.py, lib/python-beta/src/bailo/core/utils.py
This is a proposed improvement.
_Note_ : The precommit config supports Python 3.8-3.11, hence correcting the typing. See [PEP-585](https://peps.python.org/pep-0585/). Collections from `typing` are no longer standard from Python 3.9 onwards.
=> Improve dictionary typing

README.md, docker-compose-prod.yml, docker-compose.yml
Also converts the usage of `docker-compose` to `docker compose`.  `docker-compose` was deprecated in July 2023.
=> Setup Docker Compose to use replica sets

docker-compose-prod.yml, docker-compose.yml, infrastructure/helm/bailo/Chart.lock, infrastructure/helm/bailo/Chart.yaml, infrastructure/helm/bailo/values.yaml, infrastructure/nginx/nginx.conf
This PR bundles a number of changes together - happy to submit these separately if desired, and/or decouple the switch to Bitnami images.
- registry bumped from 2.8.1 to 2.8.3
- nginx switched to the 'unprivileged' variant, bumped from 1.21.6 to 1.25.4 (requires minor tweak to nginx.conf)
- mailcrab bumped from 0.10.0 to 1.2.0
- minio switched to the 'bitnami' variant, bumped from 2023.1.31 to 2024.4.6, retained default credentials
- mongodb switched to the 'bitnami' variant, bumped from 6.0.4 to 7.0.8
- bumped minio/mongodb helm dependencies to their current latest
- bumped minio/mongodb helm default image values
- removed 'version' from the docker compose files as this has been deprecated in the latest versions of compose.
=> Dependency updates for Docker & Helm

backend/src/routes/middleware/requestId.ts, backend/src/services/log.ts
Seems to cause some latency issues with deployments
=> Disable async hook performance monitoring

lib/python/src/bailo/__init__.py, lib/python/src/bailo/helper/entry.py
Code now provides a warning instead of an error if a card isn't found using the `get_card_latest()` method. This will also apply to data cards.
=> Fixed ability to retrieve models without cards

.github/workflows/build.js.yml, README.md, backend/config/docker_compose.cjs, docker-compose-prod.yml, docker-compose.yml
Whilst working on transactions, I noticed the local instance wasn't quite in replica set mode, possibly after my switch to the Bitnami image.
Authentication seems to be required, I wasn't able to force it to be disabled during dev but happy to try again or take suggestions on that. If it remains enabled, I've followed the pattern for other services of `serviceadmin` for user/pass here but happy to use something else.
It may require dropping the mongo Docker volume if you struggle to bring it up when testing these changes, though the Bitnami image 'should' adapt automatically.
=> Enable local replica set + enable basic authentication

.github/workflows/codeql.js.yml
Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> Bump codeql actions to v3

backend/src/models/User.ts, backend/src/types/types.ts
N/A
Removes duplicate user declaration at the backend
=> Remove duplicate user type

frontend/cache/config.json
If desired, this disables telemetry about commands etc being sent back to the NextJS folks.
More info: https://nextjs.org/telemetry
=> Disable next telemetry

.github/workflows/build.js.yml
Noticed this pop up a few times during PR builds. Seems like waitForIt is happy the port is open but the app isn't ready
=> Wait for backend to be ready before starting cypress

README.md, backend/nodemon.json, backend/package-lock.json, backend/package.json, backend/src/scripts/runScript.ts, backend/tsconfig.json
An initial PR for upgrading to Node 22, replaces `ts-node` with `tsx` to fix some errors with the `.ts` extension not being recognised.
=> 1. Replace ts-node with tsx

frontend/pages/model/[modelId]/access-request/schema.tsx, frontend/src/schemas/SchemaSelect.tsx
Showing inactive schemas during selection could confuse some users, especially if an organisation is trying to encourage the use of active schemas only. This change makes both active and inactive schemas appear within accordions, with active schemas shown expanded by default. Users can still expand and select an inactive schema if desired, but it's a conscious choice.
The accordion styling props is configured to remove the divider that's shown only when collapsed, and also ensure that the expand icon is justified-right all the time. If the active/inactive schema accordion is empty (no schemas) it would be misaligned with the other accordion.
=> Use accordions for schema selection, hiding inactive schemas by default

frontend/pages/data-card/[dataCardId].tsx, frontend/pages/model/[modelId].tsx, frontend/src/common/PageWithTabs.tsx
=> added a subheading and copy button to the pagewithtabs component

frontend/src/entry/model/accessRequests/AccessRequestDisplay.tsx, frontend/src/entry/model/releases/ReleaseDisplay.tsx, frontend/src/reviews/ReviewComments.tsx
=> added a review icon and count to release and access request displays

frontend/src/reviews/ReviewCommentDisplay.tsx, frontend/src/reviews/ReviewDecisionDisplay.tsx
=> improved response quoting by adding original commenter name and date

infrastructure/helm/bailo/templates/clamav/clamav.deployment.yaml, infrastructure/helm/bailo/templates/clamav/clamav.pvc.yaml, infrastructure/helm/bailo/values.yaml
- fix user issues to start clamav in aws - ref. eks security context
- fix pvc issues to allow create dynamic pvc from default storage
=> fix pvc and user

.github/workflows/web.yml
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> Fix landing page

lib/python/pyproject.toml
Hi, I'm opening this pull request as part of a push to modernise how packages use [Flit](https://flit.pypa.io/en/stable/) as a Python build backend.
Using `flit_core` as the backend in place of `flit` is [recommended in the docs](https://flit.pypa.io/en/stable/pyproject_toml.html#build-system-section), and will make it faster for tools like pip & [build](https://build.pypa.io/en/latest/) to build your package from source, as it has fewer dependencies to install.
Specifying an explicit version range (`>=2,<4`) helps to ensure that your package can still be readily built from source despite changes in future major versions of Flit, because it will still use version 3.x. For instance, a future version is likely to drop support for the `[tool.flit.metadata]` table, in favour of the …
=> Update build system to flit_core

.github/workflows/modelscan.yml, docker-compose-prod.yml, docker-compose.yml, lib/modelscan_api/.dockerignore, lib/modelscan_api/.gitignore, lib/modelscan_api/.pre-commit-config.yaml, lib/modelscan_api/Dockerfile, lib/modelscan_api/Dockerfile.dev, lib/modelscan_api/README.md, lib/modelscan_api/bailo_modelscan_api/config.py, lib/modelscan_api/bailo_modelscan_api/dependencies.py, lib/modelscan_api/bailo_modelscan_api/main.py, lib/modelscan_api/bailo_modelscan_api/test_dependencies.py, lib/modelscan_api/bailo_modelscan_api/test_main.py, lib/modelscan_api/requirements-dev.txt, lib/modelscan_api/requirements.txt
Write a Dockerfile for the REST Model Scan application.
The Dockerfile should expose the relevant ports.
The Image should be added to the dev docker compose build.
=> Dockerise our ModelScan application

.github/workflows/web.yml
To pre-emptively fix an upcoming deprecation of "Deprecation notice: v1, v2, and v3 of the artifact actions" e.g. https://github.com/gchq/Bailo/actions/runs/12254206960
> The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "github-pages".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Bump deploy-pages and upload-pages-artifact GitHub action versions

lib/python/src/bailo/core/agent.py
python library
Updated tokenagent and pkiagent to accept args and kwargs for super.__init__(), which will allow using these classes with verify=False
=> fix: enable arg & kwarg passing to superclass for sub agents

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, README.md, backend/docs/make.bat, backend/docs/notebooks/experiment_tracking_demo.ipynb, backend/docs/pylint.md, lib/modelscan_api/README.md
Fix some broken links, out if date resources and generally tidy up readmes.
Relates to #1574 but does not fully fix this problem as the legacy file is still referenced in `frontend/pages/docs/directory.tsx` and `frontend/pages/docs/administration/helm/configuration.mdx`.
=> BAI-1495 improve READMEs

.github/workflows/python.yml, backend/Dockerfile, backend/Dockerfile.dev, backend/docs/README.md, backend/docs/notebooks/access_requests_demo.ipynb, backend/docs/notebooks/datacards_demo.ipynb, backend/docs/notebooks/experiment_tracking_demo.ipynb, backend/docs/notebooks/models_and_releases_demo_pytorch.ipynb, backend/docs/notebooks/schemas_demo.ipynb, lib/python/README.md, lib/python/pyproject.toml
As per https://devguide.python.org/versions/, python 3.8 reached end of life on 2024-10-07 so no longer requires support. For the python Bailo client, we must replace all references to 3.8 with 3.9.
The Modelscan REST API already has a minimum version of python 3.9 so this does not need changing.
I also found some mismatching versions for the maximum supported python version (currently 3.11, but this needs bumping to 3.13 soon).
=> BAI-1591 drop python 3.8 support and standardise versioning

backend/src/connectors/audit/stdout.ts, backend/src/connectors/fileScanning/Base.ts, backend/src/connectors/fileScanning/clamAv.ts, backend/src/connectors/fileScanning/index.ts, backend/src/connectors/fileScanning/modelScan.ts, backend/src/connectors/fileScanning/wrapper.ts, backend/src/migrations/015_migrate_avscan_to_own_model.ts, backend/src/routes/v2/filescanning/getFilescanningInfo.ts, backend/src/routes/v2/model/file/getDownloadFile.ts, backend/src/services/file.ts, backend/src/services/mirroredModel.ts, backend/test/services/__snapshots__/file.spec.ts.snap
E.g. https://github.com/gchq/Bailo/blob/main/backend/src/connectors/fileScanning/clamAv.ts#L76
Create a function in the base scanner to unify error log and creation of the error object for all scanners. The function should take in all information needed to create a scan result and log that information.
Update uses of `file._id` to `file.id` so that the object ID is output in string form.
=> Update Scan errors

backend/Dockerfile, backend/Dockerfile.dev, frontend/cypress/e2e/bailo/check-documentation-pages.cy.ts, frontend/pages/docs/users/programmatically-using-bailo/authentication.mdx, lib/modelscan_api/Dockerfile, lib/modelscan_api/Dockerfile.dev, lib/python/src/bailo/core/agent.py
Additionally:
- Optimises `pip install` steps in Dockerfiles by utilising a cache (similar to `npm install` cache)
- Adds Cypress tests to check the documentation endpoints are accessible
=> Improve Python Agent docs

backend/src/connectors/fileScanning/Base.ts, backend/src/connectors/fileScanning/clamAv.ts, backend/src/connectors/fileScanning/index.ts, backend/src/connectors/fileScanning/modelScan.ts, backend/src/connectors/fileScanning/wrapper.ts, backend/src/routes/v2/filescanning/getFilescanningInfo.ts, backend/src/services/file.ts
- Fix async bug in delayed retry logic.
- Fix async bug in initialisation of scanners.
- Remove duplication by moving retry logic into wrapper also simplifies init logic for each scanner.
- Store scanner version on init- remove dependency on scanners after initialisation.
=> Fix bugs and refactor file scanners

lib/python/src/bailo/helper/access_request.py, lib/python/src/bailo/helper/model.py, lib/python/src/bailo/helper/release.py
Fixing issue https://github.com/gchq/Bailo/issues/1889 by removing the f-string when % formatting is used. Continuation of some logs I missed from PR #2165
=> Issue #1889: Optimise Python Client Logger Strings (Part 2)

backend/src/connectors/audit/Base.ts, backend/src/connectors/audit/__mocks__/index.ts, backend/src/connectors/audit/silly.ts, backend/src/connectors/audit/stdout.ts, backend/src/connectors/authorisation/actions.ts, backend/src/connectors/authorisation/base.ts, backend/src/models/Model.ts, backend/src/models/ReviewRole.ts, backend/src/models/Token.ts, backend/src/routes.ts, backend/src/routes/v2/review/getReviewRoles.ts, backend/src/routes/v2/review/postReviewRole.ts, backend/src/services/review.ts, backend/src/services/specification.ts, backend/test/routes/review/__snapshots__/getReviewRoles.spec.ts.snap, backend/test/routes/review/__snapshots__/postReviewRole.spec.ts.snap, backend/test/routes/review/getReviewRoles.spec.ts, backend/test/routes/review/postReviewRole.spec.ts, backend/test/services/__snapshots__/review.spec.ts.snap, backend/test/services/review.spec.ts, backend/test/testUtils/testModels.ts
Review roles are a WIP part of dynamic role work. Bailo currently relies on statically defined review roles, whereas in the future we want admins to be able to create whatever role they want for the review process.
=> Added API end points for creating and viewing review roles

lib/landing/next.config.mjs
As per https://nextjs.org/docs/architecture/nextjs-compiler#minification
> Good to know: Starting with v15, minification cannot be customized using `next.config.js`. Support for the `swcMinify` flag has been removed.
=> Remove swcMinify flag from lib/landing

lib/python/tests/test_model.py
Currently, when the Python tests are run in `/lib/python/` `pytest` will generate the warning `ID testmodel-<id> does not have any associated cards. If needed, create a card with the .card_from_schema() method.` This is expected behaviour, but appears as a warning under every PR in GitHub so looks like a potential problem when it is not.
This warning is generated at https://github.com/gchq/Bailo/blob/main/lib/python/src/bailo/helper/entry.py#L98 so any tests that call this function (e.g. `test_search_models`) need updating to capture the warning https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html
=> Expect pytest warning

backend/test/clients/cognito.spec.ts, backend/test/clients/inferencing.spec.ts, backend/test/clients/kms.spec.ts, backend/test/clients/modelScan.spec.ts, backend/test/clients/registry.spec.ts, backend/test/clients/s3.spec.ts, backend/test/connectors/authentication/oauth.spec.ts, backend/test/models/Token.spec.ts, backend/test/services/accessRequest.spec.ts, backend/test/services/inference.spec.ts, backend/test/services/model.spec.ts, backend/test/services/release.spec.ts, backend/test/services/response.spec.ts, backend/test/services/review.spec.ts, backend/test/services/schema.spec.ts, backend/test/services/smtp/smtp.spec.ts, backend/test/services/webhook.spec.ts
Fixes many instances of
> Promise returned by `expect(actual).rejects.toThrowError(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
=> add await to vitest expect reject tests

backend/src/models/Model.ts, backend/src/routes/v2/model/getModelsSearch.ts, backend/test/routes/model/__snapshots__/getModelsSearch.spec.ts.snap, lib/python/CHANGELOG.md, lib/python/src/bailo/core/agent.py, lib/python/src/bailo/core/client.py, lib/python/src/bailo/core/enums.py, lib/python/src/bailo/helper/datacard.py, lib/python/src/bailo/helper/entry.py, lib/python/src/bailo/helper/model.py, lib/python/tests/test_datacard.py, lib/python/tests/test_model.py
As a Bailo user, I would like to be able to programmatically view and add roles for specific people to a model so that I can control who uses a model without using the UI.
=> Add model collaborators get & set methods to python client

frontend/pages/model/[modelId]/release/[semver]/review.tsx
**What is the problem:** When reviewing a release, if the semver in the URL is incorrect, it causes the page to hang.
**How do I reproduce it:** Make sure to have msro/mtr perms on model, then review a release. Edit the url so the semver value is valid, but non-existent on this model.
**Expected behaviour:** It should error, displaying something along the lines of - "Error - Could not find release"
**Fix:** Problem seems to be at https://github.com/gchq/Bailo/blob/e1c6aa92e3c65b3d0f127ecb30047f63c7616b5f/frontend/pages/model/%5BmodelId%5D/release/%5Bsemver%5D/review.tsx#L119-L121
This is basically saying, if no release is found (you've supplied a non-existent semver) then display the loading animation (hangs).
A possible fix could be to just remove this, and also the `!model` and …
=> Release review with incorrect semver causes hang

backend/src/services/mirroredModel.ts, backend/test/services/mirroredModel.spec.ts
The endpoint was set up to wait for each artefact to be uploaded to S3 before completing. This is problematic when there are a large number of artefacts being uploaded as the connection may be open for a long time (and therefore risks being cut off).
This PR changes the functionality to no longer wait for each release artefact to be uploaded before returning the response.
=> Improve API `POST` `/api/v2/model/{modelId}/export/s3` endpoint time

backend/.dockerignore, backend/Dockerfile, lib/modelscan_api/.dockerignore, lib/python/CHANGELOG.md, lib/python/src/bailo/__init__.py, lib/python/src/bailo/helper/release.py, lib/python/tests/test_files.py
Python client's `Release.download_all()` did not download any files nor display any errors. Investigation shows that the problem was due to bad logic with the `include` and `exclude` filters.
This PR also includes minor improvements to the python related Dockerfiles to no longer pull in extra, unnecessary files (e.g. the tests dir and cache artefacts), and bumps the Bailo Python client package version. The new package will automatically be released upon merging this PR.
=> Python client `Release.download_all` fix

.dockerignore, backend/.dockerignore, frontend/.dockerignore, frontend/.gitignore, lib/modelscan_api/README.md, lib/python/.dockerignore
This should make builds slightly smaller, as well as improve build times by no longer pulling in unwanted files which may change and `COPY`/`ADD` commands, helping to better utilise the cached layers.
=> Improve .dockerignore and .gitignore to exclude unwanted files

lib/python/README.md
The python README is copied to https://pypi.org/project/bailo/ so requires having absolute URLs rather than relative URLs.
=> Replace relative URL with absolute URL

infrastructure/helm/bailo/templates/bailo/bailo.configmap.yaml
Gets rid of lots of noisy opentelemetry logs
=> Revert config map value to be a boolean rather than string
